### PR TITLE
Feature/integration-of-setup-video

### PR DESCRIPTION
**Pull request by vinzlange**

### CODE REVIEW

**Review by MichaelFeygelman — APPROVED** [review]

**Comment by jkoenig134** [comment]
I'm not really ok with the naming "demo website"... It's a swagger UI and used for testing out (and documenting) the connector API.

image

**Comment by vinzlange** [comment]
@MichaelFeygelman pls chaqne the name "a demo website to visualise" to "Swagger an api for testing and documentation"

**Comment by jkoenig134** [comment]
@MichaelFeygelman I'd prefer `Enable API-Docs for testing and documentation of the Connectors API`

**Comment by MichaelFeygelman** [comment]
@vinzlange und @jkoenig134 Updated Video Link: 

https://enmeshed.de/app/uploads/2024/04/Connector-aufsetzen_mit-Untertitel-1.mp4

**Comment by jkoenig134** [comment]
@MichaelFeygelman would you please also remove the `, if you don't implement it into your own system`? I think there are many use-cases enabling the api docs - most of the use cases occur WHEN you want to integrate the connector in existing systems.

**Comment by vinzlange** [comment]
i would have said, if you want to use the connector actively, use something like postman or the sdk. in both cases you don't need swagger

**Comment by jkoenig134** [comment]
- you will need a documentation to create that postman environment
- you can need additional info that's not in the sdk
- what if you don't have an SDK for your language?

**Comment by jkoenig134** [comment]
Additionally: the main point of the api docs is that the connector delivers **real time** documentation about the **actual version** that is deployed.

You can not archieve that with postman or any sdk in the world.

**Comment by vinzlange** [comment]
I import the open api spec into postman.
I just wanted to say that the docu should not be used in production systems. 
But throw out the sentence idk

**Comment by MichaelFeygelman** [comment]
@jkoenig134 und @vinzlange 

https://enmeshed.de/app/uploads/2024/05/Connector-aufsetzen_mit-Untertitel.mp4

I deleted _, if you don't implement it into your own system?_ (Starting at 1:44)

**Comment by jkoenig134** [comment]
Now I'm ok with it.

**Comment by MichaelFeygelman** [comment]
okay @jkoenig134 and @vinzlange 

but can we finally push the video on the enmeshed.eu now?

**Comment by jkoenig134** [comment]
as soon as the thumbnail is fixed i'm ok with it.

**Comment by jkoenig134** [comment]
(I mean https://enmeshed.de/app/uploads/2024/04/Thumbnail.png)

**Comment by MichaelFeygelman** [comment]
It is already fixed. 

https://enmeshed.de/app/uploads/2024/05/Thumbnail-1.png

**Comment by jkoenig134** [comment]
Ok - that's a new file. I thought you are able to update the old one. As you see in the md Thumbnail.png is still referenced, this does not get updated by magic :D

**Review by jkoenig134 — APPROVED** [review]
LGTM

**Comment by MichaelFeygelman** [comment]
@jkoenig134 Die rechte Sidebar überlagert das Video beim Scrollen. Vielleicht kriegst du das in ein kleineres Verhältnis. 

image

**Pull request merged**
